---
title: "Analise Dados"
output: html_notebook
---

```{r}
load('../cache/data_seed.RData')
library(plyr)
library(dplyr)
library(lattice)
```

## Resumo dos dados

Dados extraidos dos Google Anlytics do site Seed-MG

```{r}
print(summary(data_seed$sessions))
```


```{r}
data_seed$sessions %>% 
  dplyr::filter(sessions <= 10) %>% 
  lattice::histogram(~users, data = ., breaks = 16)
```

```{r}
data_seed$sessions %>% 
  dplyr::filter(sessions <= 10) %>%
  lattice::xyplot(sessions ~ date, data = ., type = 'l')
```
```{r}
data_seed$sessions %>% 
  dplyr::filter(sessions <= 10) %>%
  dplyr::group_by(date) %>% 
  dplyr::summarise(mean = mean(sessions)) %>% 
  lattice::xyplot(mean ~ date, data = ., type = 'l')
```

```{r}
data_seed$sessions %>% 
  dplyr::group_by(date) %>% 
  dplyr::summarise(mean = mean(users)) %>% 
  lattice::xyplot(mean ~ date, data = ., type = 'l')
```
```{r}
data_seed$sessions %>% 
  dplyr::filter(grepl('minas gerais|sao paulo|rio de janeiro', region, TRUE)) %>% 
  dplyr::group_by(date, region) %>% 
  dplyr::summarise(total = sum(users)) %>% 
  dplyr::mutate(ltotal = log10(total)) %>% 
  lattice::xyplot(ltotal ~ date, data = ., type = 'l', groups = region, auto.key = TRUE)
```

```{r}
data_seed$sessions %>% 
  dplyr::group_by(region) %>% 
  dplyr::summarise(total = sum(users)) %>% 
  dplyr::arrange(dplyr::desc(total)) %>% 
  print()
```
```{r}
data_seed$sessions %>% 
  dplyr::filter(grepl('minas gerais|sao paulo|rio de janeiro|parana|santa catarina|rio grande do sul', region, TRUE)) %>% 
  dplyr::group_by(date, region) %>% 
  dplyr::summarise(total = sum(users)) %>% 
  dplyr::mutate(ltotal = log10(total)) %>% 
  lattice::xyplot(ltotal ~ date, data = ., type = 'l', groups = region)
```
```{r}
data_seed$sessions %>% 
  dplyr::filter(grepl('minas gerais|sao paulo|rio de janeiro|parana|santa catarina|rio grande do sul', region, TRUE)) %>% 
  dplyr::mutate(period = paste0(lubridate::year(date), '-', lubridate::month(date))) %>% 
  dplyr::group_by(period, date, region) %>% 
  dplyr::summarise(total = sum(users)) %>% 
  dplyr::mutate(ltotal = log10(total)) %>% 
  lattice::xyplot(ltotal ~ date|period, data = ., type = 'l', groups = region, 
                  scales = list(x = 'free', y = 'free'))
```
```{r}
x <- data_seed$sessions %>% 
  dplyr::filter(grepl('minas gerais|sao paulo|rio de janeiro|parana|santa catarina|rio grande do sul', region, TRUE)) %>% 
  dplyr::select(date, region, users) %>% 
  dplyr::group_by(date, region) %>% 
  dplyr::summarise(users = sum(users)) %>% 
  tidyr::spread(key = 'region', 'users') %>%
  select(-2)

cor(na.omit(x[,-1]))
```


```{r}
lattice::splom(~log10(x[,-1]), pch = 16, cex = 0.5)
```

```{r}
x <- data_seed$sessions %>% 
  dplyr::filter(grepl('minas gerais|sao paulo|rio de janeiro|parana|santa catarina|rio grande do sul', region, TRUE)) %>% 
  dplyr::select(date, region, users) %>% 
  dplyr::group_by(date, region) %>% 
  dplyr::summarise(users = sum(users)) %>% 
  tidyr::spread(key = 'region', 'users') %>%
  select(-2)

xpca <- prcomp(na.omit(x[,-1]))

print(xpca)

summary(xpca)
```

```{r}
plot(xpca)
```
```{r}
print(head(data_seed$sessions))
```

